{
 "title": "Över tid - Per vecka",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  {
   "title": "Total kostnad intag av energi 2022",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Max kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> max()"
    }
   ]
  },
  {
   "title": "Medel kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> mean()"
    }
   ]
  },
  {
   "title": "Min kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> min()"
    }
   ]
  },
  {
   "title": "Total kostnad intag av energi 2023",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2023-01-01T00:00:00Z, stop: 2023-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Max kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2023-01-01T00:00:00Z, stop: 2023-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> max()"
    }
   ]
  },
  {
   "title": "Medel kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2023-01-01T00:00:00Z, stop: 2023-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> mean()"
    }
   ]
  },
  {
   "title": "Min kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2023-01-01T00:00:00Z, stop: 2023-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> min()"
    }
   ]
  },
  {
   "title": "Total kostnad intag av energi 2024",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2024-01-01T00:00:00Z, stop: 2024-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Max kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2024-01-01T00:00:00Z, stop: 2024-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> max()"
    }
   ]
  },
  {
   "title": "Medel kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2024-01-01T00:00:00Z, stop: 2024-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> mean()"
    }
   ]
  },
  {
   "title": "Min kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2024-01-01T00:00:00Z, stop: 2024-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> min()"
    }
   ]
  },
  {
   "title": "Total kostnad intag av energi 2025",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2025-01-01T00:00:00Z, stop: 2025-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Max kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2025-01-01T00:00:00Z, stop: 2025-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> max()"
    }
   ]
  },
  {
   "title": "Medel kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2025-01-01T00:00:00Z, stop: 2025-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> mean()"
    }
   ]
  },
  {
   "title": "Min kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2025-01-01T00:00:00Z, stop: 2025-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> min()"
    }
   ]
  },
  {
   "title": "Total kostnad intag av energi 2026",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2026-01-01T00:00:00Z, stop: 2026-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Max kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2026-01-01T00:00:00Z, stop: 2026-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> max()"
    }
   ]
  },
  {
   "title": "Medel kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2026-01-01T00:00:00Z, stop: 2026-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> mean()"
    }
   ]
  },
  {
   "title": "Min kostnad/vecka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2026-01-01T00:00:00Z, stop: 2026-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)\r\n |> min()"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "SEK" } },
   "targets": [
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> map(fn: (r) => ({\r\n _value: r._value,\r\n _time: r._time,\r\n _field: \"Energikostnad 2022\",\r\n }))\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)"
    },
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2023-01-01T00:00:00Z, stop: 2023-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> map(fn: (r) => ({\r\n _value: r._value,\r\n _time: r._time,\r\n _field: \"Energikostnad 2023\",\r\n }))\r\n |> timeShift(duration: -1y)\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)"
    },
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2024-01-01T00:00:00Z, stop: 2024-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> map(fn: (r) => ({\r\n _value: r._value,\r\n _time: r._time,\r\n _field: \"Energikostnad 2024\",\r\n }))\r\n |> timeShift(duration: -2y)\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)"
    },
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2025-01-01T00:00:00Z, stop: 2025-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> map(fn: (r) => ({\r\n _value: r._value,\r\n _time: r._time,\r\n _field: \"Energikostnad 2025\",\r\n }))\r\n |> timeShift(duration: -3y)\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)"
    },
    {
     "query": "from(bucket: \"ha\")\r\n |> range(start: 2026-01-01T00:00:00Z, stop: 2026-12-31T23:59:59.999Z)\r\n |> filter(fn: (r) => r[\"entity_id\"] == \"electrical_consumption_intake_cost_hour\")\r\n |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n |> map(fn: (r) => ({\r\n _value: r._value,\r\n _time: r._time,\r\n _field: \"Energikostnad 2026\",\r\n }))\r\n |> timeShift(duration: -4y)\r\n |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n |> aggregateWindow(every: 1w, fn: sum, createEmpty: true)"
    }
   ]
  }
 ]
}